# Security Integration Configuration

# Encryption Settings
encryption:
  key_rotation_interval: 86400  # 24 hours in seconds
  jwt_expiry: 3600  # 1 hour in seconds
  pbkdf2_iterations: 100000
  rsa_key_size: 2048

# Security Systems
security_systems:
  - name: "siem"
    type: "Splunk"
    api_url: "https://splunk-api.example.com"
    endpoints:
      auth: "/auth"
      alerts: "/alerts"
      status: "/status"
    features:
      - "log_analysis"
      - "threat_intelligence"
      - "incident_response"

  - name: "ids"
    type: "Snort"
    api_url: "https://snort-api.example.com"
    endpoints:
      auth: "/auth"
      alerts: "/alerts"
      status: "/status"
    features:
      - "network_monitoring"
      - "signature_detection"
      - "traffic_analysis"

  - name: "firewall"
    type: "PaloAlto"
    api_url: "https://paloalto-api.example.com"
    endpoints:
      auth: "/auth"
      alerts: "/alerts"
      status: "/status"
    features:
      - "traffic_filtering"
      - "threat_prevention"
      - "policy_management"

# Alert Configuration
alerts:
  severity_levels:
    - "critical"
    - "high"
    - "medium"
    - "low"
    - "info"
  
  notification_channels:
    - type: "email"
      recipients:
        - "security@example.com"
        - "admin@example.com"
      template: "alert_email_template.html"
    
    - type: "slack"
      webhook_url: "https://hooks.slack.com/services/xxx"
      channel: "#security-alerts"
    
    - type: "pagerduty"
      service_key: "xxx"
      escalation_policy: "security-team"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: "file"
      filename: "security.log"
      max_size: 10485760  # 10MB
      backup_count: 5
    
    - type: "syslog"
      address: "/dev/log"
      facility: "local0"

# Monitoring Configuration
monitoring:
  metrics:
    - name: "authentication_attempts"
      type: "counter"
      labels:
        - "system"
        - "status"
    
    - name: "alert_processing_time"
      type: "histogram"
      labels:
        - "system"
        - "severity"
    
    - name: "encryption_operations"
      type: "counter"
      labels:
        - "operation"
        - "status"
  
  health_checks:
    interval: 300  # 5 minutes
    timeout: 30
    retries: 3

# Backup Configuration
backup:
  schedule: "0 0 * * *"  # Daily at midnight
  retention: 30  # days
  encryption: true
  locations:
    - type: "s3"
      bucket: "security-backups"
      region: "us-west-2"
    - type: "local"
      path: "/var/backups/security"

# Compliance Settings
compliance:
  standards:
    - "ISO27001"
    - "NIST"
    - "GDPR"
  
  audit:
    enabled: true
    retention: 365  # days
    events:
      - "authentication"
      - "authorization"
      - "data_access"
      - "configuration_changes" 